"""Add min price to search agent

Revision ID: 3ddf3e6fb375
Revises: None
Create Date: 2016-10-22 11:50:55.208965

"""

# revision identifiers, used by Alembic.
revision = '3ddf3e6fb375'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_agents', sa.Column('min_price', sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_agents', 'min_price')
    ### end Alembic commands ###
