"""empty message

Revision ID: 490a65e8d12b
Revises: None
Create Date: 2016-10-31 19:35:39.618036

"""

# revision identifiers, used by Alembic.
revision = '490a65e8d12b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
