"""Rename search agent fields

Revision ID: 4ac49d076012
Revises: 3ddf3e6fb375
Create Date: 2016-10-22 11:58:53.839748

"""

# revision identifiers, used by Alembic.
revision = '4ac49d076012'
down_revision = '3ddf3e6fb375'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_agents', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('search_agents', sa.Column('keywords', sa.String(), nullable=False))
    op.drop_column('search_agents', 'agent_active')
    op.drop_column('search_agents', 'agent_keywords')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_agents', sa.Column('agent_keywords', sa.VARCHAR(), nullable=False))
    op.add_column('search_agents', sa.Column('agent_active', sa.BOOLEAN(), nullable=False))
    op.drop_column('search_agents', 'keywords')
    op.drop_column('search_agents', 'is_active')
    ### end Alembic commands ###
